USE [QLDSV_TC]
GO


-- SP_DANGNHAP
IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE
    OBJECT_ID(N'[DBO].[SP_DANGNHAP]') = OBJECT_ID AND
		TYPE IN (N'P', N'PC'))
DROP PROCEDURE  [DBO].[SP_DANGNHAP]
GO
    CREATE PROC [DBO].[SP_DANGNHAP]
    @TENLOGIN NVARCHAR (50) AS
    DECLARE @TENUSER NVARCHAR(50)
    SELECT @TENUSER=NAME FROM SYS.SYSUSERS WHERE SID = SUSER_SID(@TENLOGIN);
    
    SELECT
        USERNAME = @TENUSER,
        HOTEN = (
            SELECT HO + ' ' + TEN
            FROM GIANGVIEN
            WHERE MAGV = @TENUSER
        ),
        ROLENAME=NAME
    FROM SYS.SYSUSERS
    WHERE UID = (
        SELECT GROUPUID
        FROM SYS.SYSMEMBERS
        WHERE MEMBERUID = (
            SELECT UID
            FROM SYS.SYSUSERS
            WHERE NAME=@TENUSER
        )
    )
GO



-- SP_TAOLOGIN
IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE
    OBJECT_ID(N'[DBO].[SP_TAOLOGIN]') = OBJECT_ID AND
		TYPE IN (N'P', N'PC'))
DROP PROCEDURE  [DBO].[SP_TAOLOGIN]
GO
    CREATE PROC [dbo].[SP_TAOLOGIN]
    @LGNAME VARCHAR(50),
    @PASS VARCHAR(50),
    @USERNAME VARCHAR(50),
    @ROLE VARCHAR(50) AS

    DECLARE @RET INT
    EXEC @RET= SP_ADDLOGIN @LGNAME, @PASS, 'QLDSV_TC'
    IF (@RET =1)  -- LOGIN NAME BI TRUNG
        RETURN 1
 
    EXEC @RET= SP_GRANTDBACCESS @LGNAME, @USERNAME
    IF (@RET =1)  -- USER  NAME BI TRUNG
    BEGIN
        EXEC SP_DROPLOGIN @LGNAME
        RETURN 2
    END

    EXEC sp_addrolemember @ROLE, @USERNAME
    IF @ROLE= 'PGV' OR @ROLE= 'KHOA'
    BEGIN 
        EXEC sp_addsrvrolemember @LGNAME, 'SecurityAdmin'
    END
    RETURN 0  -- THANH CONG
GO

-- XOA_LOGIN
IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE
    OBJECT_ID(N'[DBO].[XOA_LOGIN]') = OBJECT_ID AND
		TYPE IN (N'P', N'PC'))
DROP PROCEDURE  [DBO].[XOA_LOGIN]
GO
    CREATE PROC [dbo].[XOA_LOGIN]
    @LGNAME VARCHAR(50),
    @USRNAME VARCHAR(50) AS
    EXEC SP_DROPUSER @USRNAME
    EXEC SP_DROPLOGIN @LGNAME
GO

GO
