-- master side
CREATE PROCEDURE [dbo].[SP_BDMH]
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHIBYMASV]
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHI]
CREATE PROCEDURE [dbo].[SP_CHECKID]
CREATE PROCEDURE [dbo].[SP_CHECKNAME]
CREATE PROCEDURE [dbo].[SP_CHUYENLOP]
CREATE PROCEDURE [dbo].[SP_DSSV_MH]

CREATE PROC [dbo].[SP_DANGNHAP]
CREATE PROC [dbo].[SP_INSERT_DIEM]  
CREATE PROC [dbo].[SP_REPORT_BDMH]
CREATE PROC [dbo].[SP_REPORT_BDTK]
CREATE PROC [dbo].[SP_REPORT_DSDHP]
CREATE PROC [dbo].[SP_REPORT_DSSV]
CREATE PROC [dbo].[SP_REPORT_DSTHM]
CREATE PROC [dbo].[SP_REPORT_PD]
CREATE PROC [dbo].[SP_TAOLOGIN]
CREATE PROC [dbo].[Xoa_Login]


-- side 1
CREATE PROCEDURE [dbo].[SP_BDMH]
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHIBYMASV]
CREATE PROCEDURE [dbo].[SP_CHECKID]
CREATE PROCEDURE [dbo].[SP_CHECKNAME]
CREATE PROCEDURE [dbo].[SP_CHUYENLOP]
CREATE PROCEDURE [dbo].[SP_DSSV_MH]

CREATE PROC [dbo].[SP_DANGNHAP]
CREATE PROC [dbo].[SP_INSERT_DIEM]  
CREATE PROC [dbo].[SP_REPORT_BDMH]
CREATE PROC [dbo].[SP_REPORT_BDTK]
CREATE PROC [dbo].[SP_REPORT_DSSV]
CREATE PROC [dbo].[SP_REPORT_DSTHM]
CREATE PROC [dbo].[SP_REPORT_PD]
CREATE PROC [dbo].[SP_TAOLOGIN]
CREATE PROC [dbo].[Xoa_Login]


-- side 2
CREATE PROCEDURE [dbo].[SP_BDMH]
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHIBYMASV]
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHI]
CREATE PROCEDURE [dbo].[SP_CHECKID]
CREATE PROCEDURE [dbo].[SP_CHECKNAME]
CREATE PROCEDURE [dbo].[SP_CHUYENLOP]
CREATE PROCEDURE [dbo].[SP_DSSV_MH]

CREATE PROC [dbo].[SP_DANGNHAP]
CREATE PROC [dbo].[SP_INSERT_DIEM]  
CREATE PROC [dbo].[SP_REPORT_BDMH]
CREATE PROC [dbo].[SP_REPORT_BDTK]
CREATE PROC [dbo].[SP_REPORT_DSSV]
CREATE PROC [dbo].[SP_REPORT_DSTHM]
CREATE PROC [dbo].[SP_REPORT_PD]
CREATE PROC [dbo].[SP_TAOLOGIN]
CREATE PROC [dbo].[Xoa_Login]


-- side 3
CREATE PROCEDURE [dbo].[SP_CHECKIDHOCPHI]

CREATE PROC [dbo].[SP_DANGNHAP]
CREATE PROC [dbo].[SP_REPORT_DSDHP]
CREATE PROC [dbo].[SP_TAOLOGIN]
CREATE PROC [dbo].[Xoa_Login]
